dist: xenial
sudo: required
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8
            - libmodplug-dev
            - libmpcdec-dev
            - libmpg123-dev
            - libopusfile-dev
            - libsdl2-dev
            - libsndfile1-dev
            - libsoxr-dev
            - libvorbis-dev
            - libwildmidi-dev
            - libxmp-dev

    homebrew:
        packages:
            - glib
            - libmodplug
            - libsamplerate
            - libsndfile
            - libsoxr
            - libvorbis
            - libxmp
            - mpg123
            - musepack
            - opusfile
            - sdl2

matrix:
    include:
        - os: linux
          compiler: gcc
          env:
            - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

        - os: osx
          compiler: clang

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo ln -s /usr/local/lib /usr/local/lib64

    #
    # Install libsamplerate
    #
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        cd "$HOME";
        wget 'http://www.mega-nerd.com/SRC/libsamplerate-0.1.9.tar.gz';
        tar xf libsamplerate-0.1.9.tar.gz;
        mkdir samplerate-build;
        cd samplerate-build;
        ../libsamplerate-0.1.9/configure
            --disable-dependency-tracking
            --enable-shared
            --disable-static
            --disable-gcc-opt
            --disable-sndfile
            ;
        make -j2;
        sudo make install;
      fi

    #
    # Install libopenmpt
    #
    - cd "$HOME"
    - wget 'https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-0.4.3+release.autotools.tar.gz'
    - tar xf 'libopenmpt-0.4.3+release.autotools.tar.gz'
    - mkdir openmpt-build
    - cd openmpt-build
    - ../libopenmpt-0.4.3+release.autotools/configure
        --enable-silent-rules
        --disable-dependency-tracking
        --enable-shared
        --disable-static
        --disable-openmpt123
        --disable-examples
        --disable-tests
        --disable-doxygen-doc
        --without-zlib
        --without-mpg123
        --without-ogg
        --without-vorbis
        --without-vorbisfile
        --without-pulseaudio
        --without-portaudio
        --without-portaudiocpp
        --without-sdl2
        --without-sdl
        --without-sndfile
        --without-flac
    - make -j2
    - sudo make install

    #
    # Install fluidsynth
    #
    - cd "$HOME"
    - wget 'https://github.com/FluidSynth/fluidsynth/archive/v2.0.4.tar.gz'
    - tar xf 'v2.0.4.tar.gz'
    - cd fluidsynth-2.0.4
    - mkdir build
    - cd build
    - cmake -Denable-framework=off ..
    - make -j2
    - sudo make install

    #
    # Install bassmidi
    #
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        cd "$HOME";
        wget 'http://uk.un4seen.com/files/bass24-linux.zip';
        mkdir bass;
        cd bass;
        unzip ../bass24-linux.zip;
        sudo cp bass.h /usr/local/include/;
        sudo cp x64/libbass.so /usr/local/lib/;
        cd ..;
        wget 'http://uk.un4seen.com/files/bassmidi24-linux.zip';
        mkdir bassmidi;
        cd bassmidi;
        unzip ../bassmidi24-linux.zip;
        sudo cp bassmidi.h /usr/local/include/;
        sudo cp x64/libbassmidi.so /usr/local/lib/;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        cd "$HOME";
        wget 'http://uk.un4seen.com/files/bass24-osx.zip';
        mkdir bass;
        cd bass;
        unzip ../bass24-osx.zip;
        sudo cp bass.h /usr/local/include/;
        sudo cp libbass.dylib /usr/local/lib/;
        cd ..;
        wget 'http://uk.un4seen.com/files/bassmidi24-osx.zip';
        mkdir bassmidi;
        cd bassmidi;
        unzip ../bassmidi24-osx.zip;
        sudo cp bassmidi.h /usr/local/include/;
        sudo cp libbassmidi.dylib /usr/local/lib/;
      fi

    #
    # Install wildmidi
    #
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        cd "$HOME";
        wget 'https://github.com/Mindwerks/wildmidi/releases/download/wildmidi-0.4.3/wildmidi-0.4.3-macosx.tar.gz';
        tar xf wildmidi-0.4.3-macosx.tar.gz;
        cd wildmidi-0.4.3-macosx;
        sudo cp -a *.dylib /usr/local/lib/;
        sudo cp wildmidi_lib.h /usr/local/include/;
      fi

before_script:
    - cd "$TRAVIS_BUILD_DIR"
    - mkdir build
    - cd build
    - cmake
        -DUSE_RESAMP_SRC=ON
        -DUSE_RESAMP_SOXR=ON
        -DUSE_DEC_OPENMPT=ON
        -DUSE_DEC_XMP=ON
        -DUSE_DEC_MODPLUG=ON
        -DUSE_DEC_MPG123=ON
        -DUSE_DEC_SNDFILE=ON
        -DUSE_DEC_LIBVORBIS=ON
        -DUSE_DEC_LIBOPUSFILE=ON
        -DUSE_DEC_MUSEPACK=ON
        -DUSE_DEC_FLUIDSYNTH=ON
        -DUSE_DEC_BASSMIDI=ON
        -DUSE_DEC_WILDMIDI=ON
        -DENABLE_SDLMIXER_EMU=OFF
        -DBUILD_EXAMPLE=ON
        ..

script:
    - make -j2
    - sudo make install
